require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ApiKeysController do
  before(:all) do
    @user = User.make!()
  end

  # This should return the minimal set of attributes required to create a valid
  # ApiKey. As you add validations to ApiKey, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:identifier => 123, :verification_code => "ahahhaa" }
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApiKeysController. Be sure to keep this updated too.
  def valid_session
    {:user_id => @user.id}
  end

  def make_key(args = nil)
    args ||= valid_attributes

    api_key = ApiKey.new(args)
    api_key.user = @user
    api_key.save!

    return api_key
  end

  describe "GET index" do
    it "assigns all api_keys as @api_keys" do
      api_key = make_key 

      get :index, {}, valid_session
      assigns(:api_keys).should eq([api_key])
    end
  end

  describe "GET show" do
    it "assigns the requested api_key as @api_key" do
      api_key = make_key 
      get :show, {:id => api_key.to_param}, valid_session
      assigns(:api_key).should eq(api_key)
    end
  end

  describe "GET new" do
    it "assigns a new api_key as @api_key" do
      get :new, {}, valid_session
      assigns(:api_key).should be_a_new(ApiKey)
    end
  end

  describe "GET edit" do
    it "assigns the requested api_key as @api_key" do
      api_key = make_key 
      get :edit, {:id => api_key.to_param}, valid_session
      assigns(:api_key).should eq(api_key)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ApiKey" do
        expect {
          post :create, {:api_key => valid_attributes}, valid_session
        }.to change(ApiKey, :count).by(1)
      end

      it "assigns a newly created api_key as @api_key" do
        post :create, {:api_key => valid_attributes}, valid_session
        assigns(:api_key).should be_a(ApiKey)
        assigns(:api_key).should be_persisted
      end

      it "redirects to the created api_key" do
        post :create, {:api_key => valid_attributes}, valid_session
        response.should redirect_to(ApiKey.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved api_key as @api_key" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApiKey.any_instance.stub(:save).and_return(false)
        post :create, {:api_key => {}}, valid_session
        assigns(:api_key).should be_a_new(ApiKey)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApiKey.any_instance.stub(:save).and_return(false)
        post :create, {:api_key => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested api_key" do
        api_key = make_key 
        # Assuming there are no other api_keys in the database, this
        # specifies that the ApiKey created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ApiKey.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => api_key.to_param, :api_key => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested api_key as @api_key" do
        api_key = make_key 
        put :update, {:id => api_key.to_param, :api_key => valid_attributes}, valid_session
        assigns(:api_key).should eq(api_key)
      end

      it "redirects to the api_key" do
        api_key = make_key 
        put :update, {:id => api_key.to_param, :api_key => valid_attributes}, valid_session
        response.should redirect_to(api_key)
      end
    end

    describe "with invalid params" do
      it "assigns the api_key as @api_key" do
        api_key = make_key 
        # Trigger the behavior that occurs when invalid params are submitted
        ApiKey.any_instance.stub(:save).and_return(false)
        put :update, {:id => api_key.to_param, :api_key => {}}, valid_session
        assigns(:api_key).should eq(api_key)
      end

      it "re-renders the 'edit' template" do
        api_key = make_key 
        # Trigger the behavior that occurs when invalid params are submitted
        ApiKey.any_instance.stub(:save).and_return(false)
        put :update, {:id => api_key.to_param, :api_key => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested api_key" do
      api_key = make_key
      expect {
        delete :destroy, {:id => api_key.to_param}, valid_session
      }.to change(ApiKey, :count).by(-1)
    end

    it "redirects to the api_keys list" do
      api_key = make_key 
      delete :destroy, {:id => api_key.to_param}, valid_session
      response.should redirect_to(api_keys_url)
    end
  end

end
